### ISSUE TITLE
Make the shell modifications optional

### ISSUE THREAD

**Issue by aairey** [markosamuli/ansible-linuxbrew#1]
I manage my rc files in a dotfiles repo and would not want this role to change that.

Could the include of the shell.yml be conditional?

**Comment by markosamuli** [comment]
@aairey good shout! I've pushed a new version that includes this.

Just set the following variable in your playbooks to skip `shell.yml`:

```yaml
linuxbrew_init_shell: false
```

**Comment by aairey** [comment]
Great, thanks!
